### ISSUE TITLE
[Question] how does it compare to asdf ?

### ISSUE THREAD

**Issue by setop** [Schniz/fnm#1043]
Reading the feature list - "node version manager" - it seems I use [asdf](https://github.com/asdf-vm/asdf) and its [node plugin](https://github.com/asdf-vm/asdf-nodejs) for the same usage. Asdf use a `.tool-versions` file at the root of the project directory instead of a `.node-version` file. It also allow to manage versions [hundreds of other tools](https://github.com/asdf-vm/asdf-plugins#plugin-list).
How does FNM differentiate ?

**Comment by p2edwards** [comment]
Not the author, but for me `fnm` just worked immediately. It is 'fast', like the name. For me the simplicity and speed was a differentiator. I had tried `asdf` before and I spent a while fiddling with it before settling on this. I've had zero issues with `fnm` in the years since.

Use what works for you :+1:

**Comment by Schniz** [comment]
I never used asdf. Feel free to share a benchmark if you want! I’d be happy to read a blog post that compares the two

**Comment by p2edwards** [comment]
@setop Use `--use-on-cd` during shell setup (e.g. `eval "$(fnm env --use-on-cd)"` in `.bashrc`/`.profile`)

(The install script doesn't do it automatically, but afterwards you can modify [the line it appends](https://github.com/Schniz/fnm/blob/595043f7441420e60a6ef548a560fbdd872e7533/.ci/install.sh#L203) to your shell conf file.)

https://github.com/Schniz/fnm#shell-setup

---

Impressive turnaround on those benchmarks btw! For me the most important one is shell startup time — how much delay is added when you start a new shell, or cd?

**Comment by Schniz** [comment]
The flag can indeed help with automatically changing the versions. It is not a default because he changes the behavior of the shell in some sense. The start up time is for your entire shell script? 1.3s is excessively slow for fnm, but maybe something else make it slower on your script…

In any case, I strongly recommend adding the flag to automatically switch versions. As you mentioned, this is something that I find extremely important for the best developer experience.

We even added support for the engines field in the package.json file and that can drive the automatic switching too

**Comment by thoroc** [comment]
> I also discovered that each time I switch project - which I probably do several times a day - I have to invoke `fnm use`. Else, the version from the previous project will be used instead of the version of the current project. Despite the presence of the `.node-version` file. This is very error prone and a real show stopper for me.

Works with `.nvmrc`; probably has been updated since last time you ran those test to be fair.

**Comment by Schniz** [comment]
> Ok, but I'm very surprised (maybe coming from `asdf`) it is not the default behavior

I'm considering changing this, but it is also very "violent" to change terminal defaults and run hooks. Opting in feels more natural to me as a user, but maybe I'm wrong!

**Comment by Schniz** [comment]
> Works with `.nvmrc`; probably has been updated since last time you ran those test to be fair

fnm supported `.nvmrc` from its initial version, as I wrote it while working at Wix which recommended to use nvm (they now recommend fnm <picture data-single-emoji=":galactic_relifed:" title=":galactic_relifed:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/galactic_relifed/33851380ad8f06bb.png" alt=":galactic_relifed:" align="absmiddle"></picture>), and i wanted seamless experience

**Comment by p2edwards** [comment]
I'd be curious too, because my workflow changed recently:

- I installed [`direnv`](https://github.com/direnv/direnv) so I could set some environment variables when I entered a node project or subdirectory.  
- I then installed [`jump`](https://github.com/gsamokovarov/jump) and started using it instead of `cd` to get around.
- I noticed that sometimes direnv would succeed where `--use-on-cd` missed
  - not sure if this was because I was using `j` instead of `cd`, or I was navigating less linearly (jumping to subdirectories instead of the root folder).
-  I switched to calling `fnm use` in my `.envrc` script from direnv.

So I've used `--use-on-cd` for the better part of a decade, and I like that it's bundled in, but for me it's no longer an essential feature. I stay on `fnm` because it's great at installing and switching node versions, and it's lean and reliable.
