### ISSUE TITLE
Exception while running it inside a container

### ISSUE THREAD

**Issue by vishr** [Schniz/fnm#141]
```
root@b742cde40ec0:/# fnm install v12.10.0
fnm: internal error, uncaught exception:
     (Failure "resolution failed: unknown scheme")
```

**Comment by Schniz** [comment]
Hey! What’s up? Sorry for making troubles :) 
What docket image is this?

**Comment by vishr** [comment]
I am using debian image.

**Comment by Schniz** [comment]
Okay, I have reproduced it. Looks like this is the solution (slightly based on [this reddit thread](https://www.reddit.com/r/tezos/comments/a6h7or/issue_with_tezos_client/)):

Unfortunately, the `debian` image is missing some installations and configurations out of the box:
* `/etc/services` doesn't exist, so the operating system can't unwrap `https://` calls to port 443 (and `http://` to port 80)
* the `xz-utils` package is not installed

add the following lines to `/etc/services`:

```
https           443/tcp                         # http protocol over TLS/SSL
https           443/udp                         # http protocol over TLS/SSL
https           443/sctp                        # http protocol over TLS/SSL
http            80/tcp          www www-http    # WorldWideWeb HTTP
http            80/udp          www www-http    # HyperText Transfer Protocol
http            80/sctp                         # HyperText Transfer Protocol
```

run the following command:

```
apt-get update && apt-get install -y xz-utils curl unzip
```

then fnm will work as expected.

I think this revealed a bug which we need to fix: we should have our own exception that will inform which part of the installation process didn't work. It's not clear that `resolution failed: unknown scheme` is something made by the http client (the `Cohttp` library), and then `List.hd` fails because of the compression

**Comment by vishr** [comment]
@Schniz Thanks for looking into it. I will install those dependencies and try.

**Comment by Schniz** [comment]
Cool! feel free to reopen if the problem persists! glad to (possibly) help! 😄
