### ISSUE TITLE
Getting an error when calling fnm use without .nvmrc or .node-version in current dir

### ISSUE THREAD

**Issue by klapec** [Schniz/fnm#181]
After the 1.18.0 update I noticed that calling `fnm use` in a directory that has no .nvmrc or .node-version in it results in a following error:
```
fnm: internal error, uncaught exception:
     (Failure "Nested calls to Lwt_main.run are not allowed")
```

**Comment by aantron** [comment]
@Schniz  thanks for opening the Lwt issue!

You should be able to undo the workaround now if you pin Lwt to `master`, or in a week after the 5.1.1 release, which includes the fix in Lwt (https://github.com/ocsigen/lwt/issues/758#issuecomment-569526017). I suggest trying to pin Lwt to `master` in any case, as it will help to be sure that the bug is really fixed.

**Comment by aantron** [comment]
(Although, looking at the code closer, it may indeed be better to stick with the `result` :))
