### ISSUE TITLE
question: a way to install Active LTS or Maintenance LTS

### ISSUE THREAD

**Issue by rifler** [Schniz/fnm#219]
when I install `lts/*` now (04.05.2020), it installs 12 node, but:
```
> node
Welcome to Node.js v12.12.0.
Type ".help" for more information.

> process.release.lts
undefined
```

`process.release.lts` is undefined. Otherwise it is a string in 10:
```
> node
Welcome to Node.js v10.19.0.
Type ".help" for more information.

> process.release.lts
'Dubnium'
```

My application checks expected nodejs version with installed and throw error on mismatch. Now I would like to support `lts` string in check script, but can't (without hardcoding id like `dubnium` or `erbium`)

**question:**
is there a way to specify what lts version I want to install (active or maintenance)?

**Comment by rifler** [comment]
I am sorry, `process.release.lts` is undefined, because `v12.12.0` is not LTS (but `v12.16.3` is).

but maybe this feature will be intresting. If not - you could close this issue

**Comment by Schniz** [comment]
Woah, I had no idea that `process.release.lts` returns this. So I'm not sure, when you install `lts/*` you get a non-lts version? Because we use https://nodejs.org/dist/index.json for that instead of parsing the DOM like I did when I started fnm (and I need to refactor the old code when I have time), so we should get the latest LTS version when you ask for this.
