### ISSUE TITLE
Is there way to auto-trigger on git branch changes?

### ISSUE THREAD

**Issue by edwin177** [Schniz/fnm#226]
Similar to how `--use-on-cd` triggers based on directory changes, I'd love to trigger `fnm` on git branch changes.

**Comment by Schniz** [comment]
Hey, sorry for the delay and I hope all is well.

I guess you could use the [post-checkout](https://www.git-scm.com/docs/githooks#_post_checkout) git hook for that. I don't know if this can be done globally though.

I'm closing this because this is a git issue and not fnm, but if you find a way to do that globally and you want to contribute that back to fnm, let's reopen! 👏
