### ISSUE TITLE
[Chore Feature Request]: Release file folder structure

### ISSUE THREAD

**Issue by dalisoft** [Schniz/fnm#232]
Hi @Schniz 

I currently using fnm and it works nice, but there some difficulties in installing via release files, because binaries exists within **fnm-linux** folder, can you please separate build and attach only **fnm** binary within release archive?

Thanks

**Comment by dalisoft** [comment]
Current behaviour - `fnn-linux/fnm` after extracting archive
Excepted behaviour - `fnm` after extracting archive

**Comment by dalisoft** [comment]
This makes automation to installation makes easier and much native-like for extracting directly to `/usr/local/bin`

**Comment by Schniz** [comment]
Hi and sorry for the delay!

I believe Azure Pipelines does it automatically or I just misconfigured something. I understand this idea, but it would require more work and supporting it in the installation script. Most applications do that as well (take a look at Node tarballs for example)

I'm closing this because I don't think this is very crucial but feel free to reopen if you have very strong feelings about this. Maybe I'm missing something, and it worths the hassle and wait for a PR?

(just to be clear, don't hesitate to tell me I'm wrong!)

Thanks, @dalisoft!

**Comment by dalisoft** [comment]
You are right, for my Ansible script direct installation will work better and much cleaner. 
I will try make PR to fix it when get some time. 
Thanks
