### ISSUE TITLE
fnm install npm fails on linux

### ISSUE THREAD

**Issue by alexpetrean80** [Schniz/fnm#242]
System is Fedora 32 running on an Intel I7 9850H, shell is zsh.

$ fnm install npm   
Version exists, but can't find a file for your system:
  OS:           linux
  Architecture: x64

**Comment by Schniz** [comment]
`fnm install npm` should not work. `npm` is not a valid Node version, or am I missing something? Please correct me if I do.

Please try `fnm install 14` to install Node v14 😄 

The following text:

> Version exists, but can't find a file for your system

Is definitely a bug that comes from how fnm works. This will be changed when migrating to the new Rust implementation, which uses https://nodejs.org/dist/index.json instead of parsing the HTML elements.
