### ISSUE TITLE
fnm cannot find files for arm7, debian

### ISSUE THREAD

**Issue by cdaringe** [Schniz/fnm#264]
# Problem

In an attempt to use `fnm` to install node into a debian/arm7 image, fnm fails.

`docker buildx build --platform linux/arm/v7 -f Dockerfile.esy-cache -t demo  . --load`

```
#9 [6/13] RUN fnm install 12
#9 0.773 Version exists, but can't find a file for your system:
#9 0.773   OS:           linux
#9 0.773   Architecture: x32
#9 ERROR: executor failed running [/usr/bin/linux32 /bin/sh -c fnm install 12]: runc did not terminate sucessfully
```

# Discussion

- i'm using [docker buildx](https://www.docker.com/blog/getting-started-with-docker-for-arm-on-linux/) for multi-arch support s.t. i can build for ARM on mac.
- repo for repro: https://github.com/cdaringe/freshawair/blob/demo/fnm-borked/Dockerfile.esy-cache

**Comment by Schniz** [comment]
Hey friend, the repo has been migrated to Rust, and these errors might not relate to it.
The real question is how it would know what the architecture should be. Since the original codebase wasn't meant and wasn't tested against ARM, let's move this to #222 and make this happen officially 😄 

what do you think?

In the meantime I'm closing this because fnm v1.21.0 does not support ARM architectures at all, let's hope the next versions will with your help 😄

**Comment by cdaringe** [comment]
Ya sounds good. Thx for the reply
