### ISSUE TITLE
How does this compare to Volta?

### ISSUE THREAD

**Issue by Siilwyn** [Schniz/fnm#270]
Curious how this compares to [Volta](https://github.com/volta-cli/volta), might be worth adding to the readme.

**Comment by Schniz** [comment]
Hey @Siilwyn! thanks for opening the issue.

Unfortunately, I have no idea since I have never used Volta.
Only heard about it while listening to [The New Rustacean](https://newrustacean.com/) by @chriskrycho (big fan)

Some things I see just from the website:

* They work differently (fnm is using symlinks for simplicity)
* fnm can just replace nvm (a much commonly used tool), works with `.nvmrc` and `.node-version` out of the box
* fnm does not install `yarn` or any other tools. I use [gpkg](https://github.com/Schniz/gpkg) for this. And I haven't released it yet.

I really appreciate the work being done on Volta and I'd be happy to read a blog post about it because _it is_ an interesting project from interesting people. But since Volta isn't a common tool such as nvm, I don't see the point of comparing it on the project README — and I'm closing this issue.

Feel free to reopen if you disagree or want to open a discussion.

**Comment by chriskrycho** [comment]
👋 the aforementioned mentioner-of-Volta and one of the maintainers here (thanks for the kind words!). While we certainly *hope* Volta is as popular as npm at some point, that’s a long way down the line!

We’re actually looking at how we could interop cleanly with `.nvmrc` files—had an issue pick back up [just earlier today](https://github.com/volta-cli/volta/issues/282#issuecomment-708584230)! In any case, fnm shouldn’t feel any pressure here from our POV, and I at least am happy fnm exists (speaking personally, not as a representative of Volta).

We’re happy to answer any questions, though, and if there’s a specific kind of thing you think would be interesting to blog about, we’d *love* to hear about that in particular!

**Comment by Schniz** [comment]
@chriskrycho thanks for the reply. Your Rust podcast was really awesome and made me learn so much while I was going and returning from work 😄 

Some of the things I'd be happy to read (and maybe... I need to share as well for fnm 😄)

* What's the installation process for Node?
* What's the installation process for Node packages?
  * Do you leverage npm underneath?
  * Maybe eventually you could use @zkat's [Orogene](https://github.com/orogene/orogene)? 😛 
* How does `node`, `yarn`, etc binaries just work with the right version when I'm in a Node package that defines Volta configuration? (I assume that's the case)
* How do you test Volta?
* How hard was it to support both Windows and Unix-ish machines?
* What makes Volta fast? ("because it's rust yo" might be the response but I guess it's more hard work than that 😜)

I think that Volta, nvm, n, asdf, and fnm are special tools that might feel like "magic" for some people. Although, I'm sure most people don't really think about it, take for example the ability to have multiple versions across different shells in fnm or nvm. So, it's not a standard web app. These tools have a "hidden" research baked in them to find a proper solution and I think that none of the tools share the same solution. Sharing how these tools solved some problems could be exciting — showing creativity and different tradeoffs for the paths taken.

**Comment by ljharb** [comment]
Something that also seems to happen a lot is that creators of new tools don't first have conversations with the maintainers of existing tools to learn about the tradeoffs and pitfalls - I've seen (definitely not just in version managers, but in everything) a lot of unnecessary effort, bugs, and frustration as a result of everybody having to relearn the same frictions/mistakes/successes. It'd be really interesting to see what the folks who are creative and driven enough to create new tools would do, armed with all the available experience and background.

**Comment by iwt-nduesing** [comment]
@Siilwyn  as you are curious about the differences I try to answer it. I'm not really sure if I'm right, as I use volta only for a short time and didn't really used fnm. But as I understand it fnm works like nvm. 

So with fnm and nvm you switch to the project you like to use and run `fnm use`. Then fnm scans the project for the configured version and changes the symlink to the correct version. Afterwards you can use node:
```
cd project
fnm use
node app.js
```

With volta you switch to the project (`cd project`) and use node. 
```
cd project
node app.js
```
But in this case `node app.js` doesn't run node. It runs actually volta. And volta checks your package.json. Reads the node version from there and then executed the command with that node version.

Advantages of voltas approach in difference to fnm:
- no command has to be executed before using node in a project (you can not forget it)
- no integration in the shell needed (it's just added to PATH like other programs, no `eval "$(fnm env)"` needed in `.zshrc`)

Disadvantage:
- it's executed every time you use node/yarn/... (but as it is extremely fast, I have not recognised a speed difference)

There are also some other differences in the details like different commands or different version declaration.

**Comment by jef** [comment]
> And volta checks your package.json.

This also means that any Node.js package you contribute to, must have the Volta addition. Or else the user will be using `volta` to set the Node.js version, no?

**Comment by iwt-nduesing** [comment]
Hi @jef, that is not the case. If you contribute to a node.js package you maybe check out their git repository locally and start working. If you execute some commands with node.js like running the tests, volta checks your current working directory and finds the package.json that you have checked out with the git repository. If that package.json already includes the volta block with a node version, it uses the specified version. If not, volta falls back to the node.js version you defined globally for volta on your computer but the package.json keeps unchanged. To add the version to the project, you have to execute for example `volta pin node@lts` or `volta pin yarn` or what you like to pin. So if a project doesn't uses volta, you can still use volta like you use nvm or fnm by setting your global/fallback node version with `volta install node@12`.

**Comment by JanJakes** [comment]
For me, the most notable difference from the user perspective is the way of switching Node versions per project:

**NVM/FNM:**
- Running `nvm use` or `fnm use` every time is not very convenient for me.
- With NVM I used the [deeper shell integration](https://github.com/nvm-sh/nvm#deeper-shell-integration) that switches Node version on every `cd` command but then the command itself became painfully slow.
- I haven't tried it but I believe `fnm` could improve the performance significantly when using deeper shell integration (I guess the same script should work also with `fnm`).
- Deeper shell integration still seems a bit "hacky" to me although for all standard use cases (change directory, run some commands, etc.) it probably works great, I'm not sure what happens when something is executed from a different directory, etc.

**Volta:**
- Volta solved the above problems for me completely – commands like `cd` are not affected at all, node always uses the correct version, and it's super-fast.
- Some downsides for me are having to add the `volta` section in `package.json` (when files like `.nvmrc` and `.node-version` already exist and `package.json` already has a `packageManager` clause) and in workspaces having to add it to every package with [an extends clause](https://docs.volta.sh/advanced/workspaces).
- I also find it a bit confusing that Volta can install any package binaries and pin them to specific Node versions (it adds some complexity together with local/global npm/yarn installs) but apart from Node & Yarn I always install everything in the project itself so I'm simply not using these features.

**Comment by Schniz** [comment]
Why do you consider fnm and nvm "deep shell integration" hacky? zsh and fish both have hooks, which are meant exactly for that

I am considering adding a "Volta"-ish methods to fnm as well as discussed in another issue (adding binstub will practically allow for Volta like usage) but I really don't consider the extremely fast automatic version switching of fnm to be hackier than Volta.

**Comment by JanJakes** [comment]
@Schniz Maybe you're right it's not any more hacky than Volta and maybe it's only about the impression I get when seeing this:

> If you prefer a lighter-weight solution, the recipes below have been contributed by nvm users. They are not supported by the nvm maintainers. We are, however, accepting pull requests for more examples.

And this:
```bash
cdnvm() {
    cd "$@";
    nvm_path=$(nvm_find_up .nvmrc | tr -d '\n')

    # If there are no .nvmrc file, use the default nvm version
    if [[ ! $nvm_path = *[^[:space:]]* ]]; then

        declare default_version;
        default_version=$(nvm version default);

        # If there is no default version, set it to `node`
        # This will use the latest version on your machine
        if [[ $default_version == "N/A" ]]; then
            nvm alias default node;
            default_version=$(nvm version default);
        fi

        # If the current version is not the default version, set it to use the default version
        if [[ $(nvm current) != "$default_version" ]]; then
            nvm use default;
        fi

        elif [[ -s $nvm_path/.nvmrc && -r $nvm_path/.nvmrc ]]; then
        declare nvm_version
        nvm_version=$(<"$nvm_path"/.nvmrc)

        declare locally_resolved_nvm_version
        # `nvm ls` will check all locally-available versions
        # If there are multiple matching versions, take the latest one
        # Remove the `->` and `*` characters and spaces
        # `locally_resolved_nvm_version` will be `N/A` if no local versions are found
        locally_resolved_nvm_version=$(nvm ls --no-colors "$nvm_version" | tail -1 | tr -d '\->*' | tr -d '[:space:]')

        # If it is not already installed, install it
        # `nvm install` will implicitly use the newly-installed version
        if [[ "$locally_resolved_nvm_version" == "N/A" ]]; then
            nvm install "$nvm_version";
        elif [[ $(nvm current) != "$locally_resolved_nvm_version" ]]; then
            nvm use "$nvm_version";
        fi
    fi
}
alias cd='cdnvm'
cd $PWD
```

And having to copy-paste this manually...
And once for each shell (if you have multiple)...

And it hooks on `cd` so the switching is a kind of a "side-effect" of `cd` which may not catch all cases, right?
- Do we always land in a directory using the `cd` command?
- What if your monorepo has multiple Node versions and some scripts need to call other ones from different directories?
- Can this aliased `cd` break the original `cd` in some edge cases?

Compared to the above Volta "just works" when you install it.

**Comment by ljharb** [comment]
It’s not that it’s hacky, it’s that it’s too intrusive to be done by default. Volta uses a “shims” approach, so it’s always hijacking your commands and routing them to the actual underlying binaries, where nvm and fnm use a PATH approach, so you’re always getting directly to the underlying binaries.

In other words, convenience aside, if anything the hackiest approach is a shims-based one.

**Comment by Sheepeer** [comment]
Having used both fnm and volta, I hold volta fits projects which has package.json, and it manages more than node but yarn/npm etc. Whereas fnm is just like a nvm with auto-changing node version function. For me, if only need to restrict node version, I preffer fnm.
