### ISSUE TITLE
Why fnm insert its tmp dir to path second time when enter tmux session

### ISSUE THREAD

**Issue by owarai** [Schniz/fnm#358]
Thanks for your work on this amazing tool.

I encountered a small problem when use it.

**Description:**

I add `~/.config/fish/conf.d/fnm.fish` with content: `fnm env | source`.

When I opened a fresh terminal and print PATH variable:
```
/tmp/fnm_multishell_65447_1610203132978/bin /opt/openresty/bin /home/max/.local/bin /usr/local/bin /usr/bin /bin ...(omit others)
```

Then I enter in my tmux session and print it again:
```
/tmp/fnm_multishell_65852_1610203429623/bin /opt/openresty/bin /home/max/.local/bin /tmp/fnm_multishell_65447_1610203132978/bin /usr/local/bin /usr/bin /bin ...(omit others)
```

**Comment by Schniz** [comment]
This is because your login shell is fish too. So you run `fnm env | source` twice: one when you open a shell session (a new tab or split in your shell, or just.. a shell) and one when you launch tmux, which starts a shell. It's not different than any other configuration you put in your shell config. 

You can do some scripting to only call fnm when you're on tmux. I believe tmux sets `$TMUX` which you can use in your condition

**Comment by owarai** [comment]
Thanks.

According to your explanation, I wrote this new `fnm.fish` to handle this problem(For people encountered this issue like me):

```
if set -q TMUX
  exit
end
if command -q fnm
  fnm env | source
end
```
