### ISSUE TITLE
Suggestion, prefer .fnmrc over .nvmrc if both exists

### ISSUE THREAD

**Issue by jrylander** [Schniz/fnm#360]
Seems logical and would help when a syntax in nvmrc is not supported.

**Comment by jrylander** [comment]
.nvmrc is has precedence in zsh using "fnm env --use-on-cd"

**Comment by Schniz** [comment]
There is no `.fnmrc`, and I don't think we should have, since there is enough fragmentation in the community.

BUT we do support `.node-version` and **I agree** it should have higher-precedence than `.nvmrc`.

https://github.com/Schniz/fnm/blob/2e313ab03e420023de3cb28b18335295f5685f0c/src/version_files.rs#L8

Should be an easy fix with a somewhat easy test 😄 
Would you like to make the change?

**Comment by jrylander** [comment]
Hehe. Indeed. Will do. (and investigate why I see a .fnmrc being used :) )

**Comment by Schniz** [comment]
Maybe relates to the fish fnm? https://github.com/Schniz/fnm/issues/3

**Comment by jrylander** [comment]
Please accept my apologies, I do not have the time since my priorities have changed. Tnx for your software!
