### ISSUE TITLE
fnm should be on the package manager list in Node.js site

### ISSUE THREAD

**Issue by wildcard** [Schniz/fnm#367]
https://nodejs.org/en/download/package-manager/

**Comment by Schniz** [comment]
Let's do it. Can you open a PR for Node? 😃

**Comment by wildcard** [comment]
I'll try 🙈

**Comment by wildcard** [comment]
@Schniz this is the file to edit https://github.com/nodejs/nodejs.org/blob/master/locale/en/download/package-manager.md

Do you have a copy I can use there? An explanation about fnm and why it's better than nvm & nodenv 😛

**Comment by Schniz** [comment]
What you sent me in TG was good:

```
## fnm
Fast and simple Node.js version manager built in Rust used to manage multiple released Node.js versions. It allows you to perform operations like install, uninstall, switch Node versions automatically based on the current directory, etc.
To install fnm, use this [install script](https://github.com/Schniz/fnm#using-a-script-macoslinux).
```

> why it's better than nvm & nodenv

I not sure I would say that it is better than nvm or nodeenv, since I truly respect people who choose or build other tools.

I _would_ say that it works on every platform (OSX, Windows, Linux), on every shell (Bash, Zsh, Fish, PowerShell, Windows Command Line Prompt...), and is very very fast.

**Comment by wildcard** [comment]
nodejs/nodejs.org#3645 is merged now

**Comment by Schniz** [comment]
👏 bravo and thanks 🙏
