### ISSUE TITLE
Use `engines` in modules where it is defined

### ISSUE THREAD

**Issue by bnb** [Schniz/fnm#39]
There's a `package.json` property called `engines`. This property can be used for anything, but one of the few defined engines is `node`. It's extremely unfortunate that it's not been used in tooling like `fnm` yet, and would be incredible to see `fnm` adopt it as a version indicator.

The added complexity here will be around version ranges, since semver ranges are entirely within scope for this field.

Ideally, it would be _absolutely incredible_ if I could run `fnm` inside of a directory with the `engines` property defined and be presented with my options.

- Show a row for each acceptable release line
	- Prioritize the versions I've already got installed that match those releases
	- Show (via green/red text) if I don't have any versions installed that match the range and offer to install if I want to use that release line 

Engines documentation in the `npm-package.json` docs: https://docs.npmjs.com/files/package.json#engines

**Comment by ljharb** [comment]
the engines field is purely advisory, and “these versions are supported” doesn’t in any way imply which version should be used - however, if it interactively asks you which supported engine you want, that seems like it’d work great.

**Comment by Schniz** [comment]
Hey and thanks for the issue. `engines` is a good thing to do, but I think we can just "warn" that the current directory expects a version that you don't currently use or have installed

I agree with @ljharb - that I can't know which version you'd like to install. `node: ">= 4"`, should I install/use latest?

**Comment by Schniz** [comment]
what do you think @bnb? how do you imagine it working?

**Comment by Schniz** [comment]
Closing it because I can't see how it would be used. Feel free to reopen if you do have an idea (and think that it will be any good)

**Comment by heppokofrontend** [comment]
Thanks for the great tool!
However, I was looking for this Issue.

I work for a company that has a lot of projects, and their projects have the following features.

- The `engines` prop in `package.json` has the version of `node`.
- There is a `.npmrc` file with [`engine-strict=true`](https://docs.npmjs.com/cli/v8/using-npm/config#engine-strict) or a `.node-version` file just exists.

> Hey and thanks for the issue. engines is a good thing to do, but I think we can just "warn" that the current directory expects a version that you don't currently use or have installed

Indeed, I too think it should be limited to a warning.
However, I feel it is a great idea to adopt it as a hint when `fnm install`.

Can't you refer to `n` as a version solution?
I usually use macOS, but I am a Windows user at work.
https://github.com/tj/n#specifying-nodejs-versions

Thank you🥒

**Comment by heppokofrontend** [comment]
@Schniz Thanks for the great tool!
However, I was looking for this Issue.

I work for a company that has a lot of projects, and their projects have the following features.

- The `engines` prop in `package.json` has the version of `node`.
- There is a `.npmrc` file with [`engine-strict=true`](https://docs.npmjs.com/cli/v8/using-npm/config#engine-strict) or a `.node-version` file just exists.

> Hey and thanks for the issue. engines is a good thing to do, but I think we can just "warn" that the current directory expects a version that you don't currently use or have installed

Indeed, I too think it should be limited to a warning.
However, I feel it is a great idea to adopt it as a hint when `fnm install`.

Can't you refer to `n` as a version solution?
I usually use macOS, but I am a Windows user at work.
https://github.com/tj/n#specifying-nodejs-versions

Thank you🥒

**Comment by Schniz** [comment]
> Can't you refer to `n` as a version solution? I usually use macOS, but I am a Windows user at work. [tj/n#specifying-nodejs-versions](https://github.com/tj/n#specifying-nodejs-versions)

What do you mean here?



> Indeed, I too think it should be limited to a warning. However, I feel it is a great idea to adopt it as a hint when `fnm install`.

Do you think it should be treated the same as `.node-version` or `.nvmrc` files? As in -- an automatic input for `fnm use`?

**Comment by heppokofrontend** [comment]
> What do you mean here?

Sorry, I didn't explain myself well enough.

Most of the people in my company uses Nodist on Windows.
That's why the `.node-version` file is included in most of our git projects.
I want to stop using Nodist and use fnm.

On the other hand, some projects that don't have a `.node-version` file specify the Node.js version by `engines` of `package.json` along with the `.npmrc` file.

I think that using fnm instead of [nodist](https://github.com/nullivex/nodist) is great. However, I'd be more than happy to use the `engines` in `package.json` as a hint for version switching, just like nodist.

> Can't you refer to n as a version solution?
> I usually use macOS, but I am a Windows user at work.

I thought that I talked about Windows, and then I talked about [n](https://github.com/tj/n#specifying-nodejs-versions) ( n does not support Windows). So, I wrote this. 
I am not used to writing in English. I am sorry.

> Do you think it should be treated the same as .node-version or .nvmrc files? As in -- an automatic input for fnm use?

Yes! However, I think `engines` should be referred to as a last resort when no other hints are available.

**Comment by vanyauhalin** [comment]
> I agree with @ljharb - that I can't know which version you'd like to install. `node: ">= 4"`, should I install/use latest?

I thinks that it would be great to offer to install latest lts version. In case the set high version limit (`node: ">=14 <16"`), still offer to install the latest lts (`16.14.2`).

**Comment by andrefcdias** [comment]
> I agree with @ljharb - that I can't know which version you'd like to install. `node: ">= 4"`, should I install/use latest?

That can be solved by using a `semver` library (like this one https://docs.rs/semver/ or this one https://docs.rs/node-semver/) and matching what's defined in the `engines` against the available remote versions from node.js.
I feel that this functionality is key for users who want to have range matching, like for example "^14.17.0 || ^16.0.0" and parity with what's used in their CI, since nvm/.nvmrc only supports fixed versions and does not intend on supporting it.

**Comment by bnb** [comment]
> I thinks that it would be great to offer to install latest lts version. In case the set high version limit (node: ">=14 <16"), still offer to install the latest lts (16.14.2).

this is correct. This is how semver works and it's (imo) what users expect.

**Comment by xdumaine** [comment]
@Schniz I'd propose you use the latest matching version installed on the system (when there's no upper bound) and the latest matching version (when there is an upper bound) As others have said. This would be really nice to avoid duplication/fragmentation since we use `engines` across all of our repos. Any chance we could re-open to consider that?

**Comment by ysmood** [comment]
I just created a tool to solve this issue, please give it a try: https://github.com/ysmood/use-node

**Comment by matchai** [comment]
With the proliferation of [corepack](https://nodejs.org/api/corepack.html), we're now keeping our package manager versioned with the `packageManager` key of our `package.json` files. It stands to reason that we should be similarly respecting `engines.node` so that runtime versions are colocated, with your project's Node.js version living alongside your project's package manager version.
I'd love to see this issue reopened for consideration.

**Comment by bnb** [comment]
hey @Schniz just wanted to check to see if you'd reconsider given the number of people here who've voiced that it'd be useful for them <3

**Comment by theoephraim** [comment]
@Schniz might be useful to refer to some of the discussion in https://github.com/nvm-sh/nvm/issues/651 that has been going on since 2015! The main justification for not implementing it there is not wanting to parse the JSON file. Clearly there are a lot of folks who want this feature, and while yes there are many tradeoffs to consider, using it as a last resort when no version is found in the prescribed files, and when a specific version can be inferred, seems like a very reasonable thing to do.

When I say infer a version, I mean that while building libraries, one may have a very wide range, so inferring may not really make sense, but usually for an internal project, you would have a specific version you're running in prod, and you'd like all your environments to match that. In this case, having the tool infer that you want to use 1.2.3 from a range string of "1.2.3" or "~1.2.3" seems quite reasonable, no? Even in the library case, choosing the highest end of the range could probably be fine in many cases, as long as it's a closed range.

**Comment by Schniz** [comment]
I didn’t have time to publish the latest version, but https://github.com/Schniz/fnm/commit/3da0fda313724d38a77fe28fae33caae2df0de08 which is the next version will contain an experimental flag that will support this feature! Cc @bnb @theoephraim 
Kudos to @amitdahan  on a very long PR

**Comment by mrienstra** [comment]
Looks like the current status is:
1. Available in `fvm` releases >= [1.35.0](https://github.com/Schniz/fnm/blob/master/CHANGELOG.md#1350), "via experimental `--resolve-engines` flag"
2. Maybe this behavior will become the default starting with `fnm` v2...? Is that on the roadmap, and are there hurdles to clear to make that possible? Given that this issue has been closed, does it make sense to open a new issue (or start a "discussion") to track the road to "respect `"engines"` by default"?

**Comment by uncenter** [comment]
For those coming across this later like me, [fnm >= 1.38.0](https://github.com/Schniz/fnm/releases/tag/v1.38.0) (released Nov 14, 2024) has the `--resolve-engines` flag enabled by default.
