### ISSUE TITLE
fnm on Apple M1 can't find a prebuilt binary on nodejs.org

### ISSUE THREAD

**Issue by vikiival** [Schniz/fnm#402]
I'm using 🍏 M1
Installed fnm via `brew install --build-from-source fnm`

When I want to install any node version (like `fnm install 15`) I get following error
```
Can't download the requested version: Can't find version upstream
```

**Comment by Schniz** [comment]
Unfortunately, fnm does not build Node from source, and right now Node has no prebuilt M1-compatible binaries in their downloads page (https://nodejs.org/dist)

Sadly I don't own M1 (yet..? who knows), and there is no CI that allows testing against M1 machines, so I can't really fix that and test my fixes. My idea is to download regular Node builds and run them with Rosetta. But all of this is gibberish to me and buzzwords I heard over the internet because again, I don't own an M1.

I'd be veeeeeeery happy to see a contribution that allows that or even pointing me towards some CI service I can use to get very slow feedback, but at least some feedback, for fixing the issue for users.

**Comment by pckilgore** [comment]
In the interim, would it be possible to expose an option allowing us to select a specific arch?  M1's run node x86 just fine through Rosetta 2, the immediate blocker is that I can't seem to coax fnm into doing that.

**Comment by iddar** [comment]
I solve this issue use a Home brew under `arch -x86_64 ` (aka ibrew) to instal a `x86_64` version to `fnm` 

```sh
alias ibrew='arch -x86_64 /usr/local/bin/brew'
❯ ibrew install --build-from-source fnm
```

Check your package arch with 

```sh
❯ file $(which fnm)
/usr/local/bin/fnm: Mach-O 64-bit executable x86_64

```

Don't is an ideal way ut works for now

**Comment by pckilgore** [comment]
> I solve this issue use a Home brew under `arch -x86_64 ` (aka ibrew) to instal a `x86_64` version to `fnm`

This seems to require a separate version of homebrew, as the ARM64 homebrew refuses to run those commands.

@Schniz happy to help with a PR here if you're OK with exposing an --arch option on install.

**Comment by Schniz** [comment]
Thanks to @pckilgore, fnm v1.24.0 now will install the binaries that can run using Rosetta. So I'm closing this issue. Thanks for reporting! 😃
