### ISSUE TITLE
Have you thought about being able to install node local to a project?

### ISSUE THREAD

**Issue by from-nibly** [Schniz/fnm#41]
So in a lot of my projects I put a ./appw file that will start the app from absolute scratch even if you don't have node or nvm installed anywhere. It is kind of janky because nvm was not built to do this. Have you ever considered adding a supported mode where you could install fnm local to a project directory and install node versions alongside it?

psuedo code script example
```bash
#install fnm
curl -0 .fnm/bin/fnm ...
export PATH=`pwd`/.fnm/bin:$PATH
fnm install # via package.json
fnm use
export PATH=`pwd`/.fnm/node-versions/${NODE_VERSION} #some way to get this from .nvmrc?
if [ ! -d 'node_modules' ]; then # you can also use the hash of the package.json file to check
  npm install
fi
exec npm start || node app/index.js || ts-node app/index.ts
```

**Comment by Schniz** [comment]
There's an environment variable that you can provide to tell which directory will be the root:

https://github.com/Schniz/fnm/blob/7bc7e85801aab41679f2b746cf6f839fd4df0c6d/library/Config.re#L40-L53

I use it on the feature tests:

https://github.com/Schniz/fnm/blob/7bc7e85801aab41679f2b746cf6f839fd4df0c6d/feature_tests/run.sh#L27

Is that what you're looking for?

also, I need to make it an option to `fnm env`, because I believe this will be easier to follow (`fnm env --help` will tell you anything you can configure)

**Comment by from-nibly** [comment]
Oh dang! That is like 90% of what I need!

I just made a pr for parameterizing the install script. https://github.com/Schniz/fnm/pull/48

**Comment by Schniz** [comment]
I'm closing this because I think it is already feasible with #48 and #49
