### ISSUE TITLE
Linux with X11 can't infer shell

### ISSUE THREAD

**Issue by latipun7** [Schniz/fnm#684]
My current user has default shell to `zsh`.
My `.xprofile` sourcing `.zshenv` which has the following lines:
```zsh
if hash fnm &>/dev/null; then
  export FNM_DIR="$XDG_DATA_HOME/fnm"
  eval "$(fnm env --use-on-cd)"
  echo "shell: $SHELL" 1>&2
fi
```
But after login, I have errors in `.xsession-errors` file (right at the top of file has this following lines):
```log
error: process ID out of range

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
shell: /usr/bin/zsh
shell: /usr/bin/zsh
```

### Environments
OS: Arch Linux x86_64 (Desktop with Xorg server)
FNM: 1.31.0

Let me know what additional infomations that I need to provide, and sorry if this seems diplicate issue.

Thanks for the hardwork and help.

**Comment by Schniz** [comment]
Yeah it makes sense. The error comes because we can't infer the _current_ shell, because it's not running in a shell context--it's running within an X11 context.

I would also argue that `--use-on-cd` make no sense when running in X11 as you don't `cd` within an X11 context (AFAIK). X11 will probably not going to support `--shell=zsh` or any other zsh-related functions because I believe X11 is running in a `sh`-like environment or `bash` at most. If that's the case, your `.zshenv` can only use the lowest common denominator of functions which is unfortunate--you can't leverage any of Zsh features like hooks.

So, I'd suggest not running `fnm env --use-on-cd` within your `.xprofile`, and opt for `fnm env` instead. Keep `--use-on-cd` in `.zshrc` so it will only be applied in Zsh sessions.

You can also try using `fnm env --shell=bash --use-on-cd`, but I am not sure that it will even work (and wouldn't recommend on doing so).

Let me know how that works out!

**Comment by latipun7** [comment]
> I would also argue that `--use-on-cd` make no sense when running in X11 as you don't `cd` within an X11 context (AFAIK). 

Ah, yes. I still have `--use-on-cd` because I'm sourcing this from `.zshenv`. I'm fine without `--use-on-cd` on X11.

> You can also try using `fnm env --shell=bash --use-on-cd`, but I am not sure that it will even work (and wouldn't recommend on doing so).

This is work if I have `fnm env --shell=bash`. But, since that file is needed when I open shell, how do I conditionally `fnm env --use-on-cd` if I'm on shell and `fnm env --shell=bash` if I'm login in X11?

I guess, `$SHELL` still print zsh even I don't open terminal and enter the shell 🤔
