### ISSUE TITLE
Problems with installing with `--skip-shell` flag

### ISSUE THREAD

**Issue by johnletey** [Schniz/fnm#82]
When I run `curl https://raw.githubusercontent.com/Schniz/fnm/master/.ci/install.sh | bash -s --skip-shell`, I get the following error:

```sh
bash: --: invalid option
Usage:	bash [GNU long option] [option] ...
	bash [GNU long option] [option] script-file ...
GNU long options:
	--debug
	--debugger
	--dump-po-strings
	--dump-strings
	--help
	--init-file
	--login
	--noediting
	--noprofile
	--norc
	--posix
	--protected
	--rcfile
	--restricted
	--verbose
	--version
	--wordexp
Shell options:
	-irsD or -c command or -O shopt_option		(invocation only)
	-abefhkmnptuvxBCHP or -o option
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3650  100  3650    0     0   5182      0 --:--:-- --:--:-- --:--:--  5184
(23) Failed writing body
```

However, if I just run `curl https://raw.githubusercontent.com/Schniz/fnm/master/.ci/install.sh | bash`, it works fine

**Comment by Schniz** [comment]
Whoops, it didn't worked as I thought it'd be. Seems like we need to add another `--` to it, so Bash wouldn't think that `--skip-shell` is an argument for itself:

```
curl https://raw.githubusercontent.com/Schniz/fnm/master/.ci/install.sh | bash -s -- --skip-shell
```

Doesn't look as good! we also need to fix it in a PR. Sorry about that! The installation script _isn't tested at all_. This is a problem. Do you think we should test in on CI? It could fail because we try to get information from GitHub 🤷‍♂️

**Comment by Schniz** [comment]
I have added it to the README. I'm opening it to discussion

**Comment by johnletey** [comment]
> Do you think we should test in on CI? It could fail because we try to get information from GitHub 🤷‍♂️

@Schniz I feel like we could test it on a CI, I don't think it would fail

**Comment by Schniz** [comment]
@johnletey I hope I'll have time for it today. It'll be weird installing an older version on every build, but `fnm --version` should always work, so we should be good!

**Comment by johnletey** [comment]
@Schniz Thank you so much!

**Comment by moshfeu** [comment]
> I have added it to the README. I'm opening it to discussion

Not here :(
https://github.com/Schniz/fnm#upgrade

Also, `curl https://raw.githubusercontent.com/Schniz/fnm/master/.ci/install.sh | bash -s -- --skip-shell` seems like requires also `--force-install`

> MacOS installation works better using Homebrew.
Please consider installing using:
    $ brew install Schniz/tap/fnm
or run the script again with the `--force-install` option.

**Comment by Schniz** [comment]
@moshfeu I understand that the hierarchy is wrong. Is that what you’re trying to say here? Have you installed using homebrew? `brew upgrade fnm` should do the trick for you.

**Comment by Schniz** [comment]
And if you haven’t installed with homebrew, why?

**Comment by moshfeu** [comment]
I meant that in the readme, the section `upgrade` doesn't mention the command `curl https://raw.githubusercontent.com/Schniz/fnm/master/.ci/install.sh | bash -s -- --skip-shell`.
And also wanted to say that just to add `--skip-shell` is not enough and you have to add `--force-install`. So my suggestion is to add in the `upgrade` section, the full command: 

    curl https://raw.githubusercontent.com/Schniz/fnm/master/.ci/install.sh | bash -s -- --skip-shell --force-install

> And if you haven’t installed with homebrew, why?
Because I didn't want to wait until `homebrew` will update itself..
