### ISSUE TITLE
Feature request: support "GitHub Actions" shell

### ISSUE THREAD

**Issue by papb** [Schniz/fnm#831]
I am trying to use fnm in a GitHub Action with no luck.

[GitHub Actions have a special way of setting environment variables](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable), and apparently simply using `export` does not work (which is what `fnm env` currently does).

Can you add support for GitHub Actions? It would probably involve things like:

```
echo "/home/runner/.fnm" >> $GITHUB_PATH

echo "FNM_NODE_DIST_MIRROR=$FNM_NODE_DIST_MIRROR" >> $GITHUB_ENV
```

**Comment by Schniz** [comment]
can I ask why using fnm and not `setup-node` in github actions which is the standard way of installing Node.js on GitHub Actions?

**Comment by papb** [comment]
I wanted to run a bash script like this:

```
for version in 6 8 10 12 14 16 18; do
    fnm use $version
    # do something here
done
```

**Comment by Vap0r1ze** [comment]
https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#example-using-a-single-dimension-matrix

**Comment by papb** [comment]
Hi @Vap0r1ze thanks and sorry I wasn't clear on what I wanted above. Here's an updated script that better show my needs:

```bash
# do something expensive before

for version in 6 8 10 12 14 16 18; do
    fnm use $version
    # do something here
done

# do something expensive after
```

Therefore I don't want to split it in a GitHub Actions matrix.

**Comment by Vap0r1ze** [comment]
@papb I still don't get why this cant be a matrix job, do your "before" actions generate files that you need in the for loop?

**Comment by Schniz** [comment]
> I still don't get why this cant be a matrix job

<picture data-single-emoji=":same:" title=":same:"><img class="emoji" width="20" height="auto" src="https://single-emoji.vercel.app/api/emoji/eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..NQISl2rxxTM65VWb.oXBZ8ux1zb5BfQdxZtJUo2S46gie_lboJLwAsRUsx8r7PwaApqI2-AqaisOA21sL4o5k-QNqrVSqPHPORSh87Gh7sY1hnG_Wtb3SaCZ9leEuQQFTUsc.BpJNgsyVzfwrP2qKx4RPHw" alt=":same:" align="absmiddle"></picture> 


you can have something like:

```yaml
jobs:
  pre_expensive:
    steps: ...

  per_version:
    needs: pre_expensive
    strategy:
      matrix:
        node_version: [6.x, 8.x, 10.x]
    steps: ...

  # optional, after version-specific
  post_expensive:
    steps: ...
```

Closing this for now, because fnm is not meant to be used like that.
_That being said_ I am 100% considering having a `fnm env --shell=json` so one can implement something like that in userland.

**Comment by papb** [comment]
Oh cool, I did not think of that. Thank you very much @Vap0r1ze abd @Schniz!

> That being said I am 100% considering having a fnm env --shell=json so one can implement something like that in userland.

Awesome!
