### ISSUE TITLE
PowerShell path on WIndows is incorrect

### ISSUE THREAD

**Issue by titotegard** [Schniz/fnm#969]
In the [set up your shell for fnm](https://github.com/Schniz/fnm#shell-setup), on windows the folder should be ~\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1

**Comment by Schniz** [comment]
citation?
I believe [the docs](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.3#profile-types-and-locations) mention the path we're suggesting, but I might parsing them wrong.

**Comment by titotegard** [comment]
In the [the docs](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.3#profile-types-and-locations) section "Profiles and remote sessions" it says "$HOME\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1". 

At first, I'm confused why my fnm env variable doesn't work when I use "$HOME\Documents\PowerShell\Microsoft.PowerShell_profile.ps1", but when I check my $PROFILE, the default is "$HOME/Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1"

I'm newbie in using PowerShell, so I just want you to know about this.

**Comment by titotegard** [comment]
In the [the docs](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.3#profile-types-and-locations) section "Profiles and remote sessions" it says "$HOME\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1". 

At first, I'm confused why my fnm env variable doesn't work when I use "$HOME\Documents\PowerShell\Microsoft.PowerShell_profile.ps1", but when I check my $PROFILE, the default is "$HOME/Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1"

I'm newbie in using PowerShell, so I just want you to know about this. This is my first time to post issue in gihtub, so pardon me if I still figuring this "Issue" out.

**Comment by mikerochip** [comment]
`~\Documents\WindowsPowerShell\` is probably "Windows PowerShell" aka the built-in PowerShell

`~\Documents\PowerShell\` is "PowerShell 7" aka the newer, cross-platform PowerShell that's not built-in

@titotegard probably the Microsoft documentation just hasn't been updated properly. The official PowerShell documentation in general is a bit weird - a lot of it is copy/pasted from articles and books.

Anyway, the fnm shell setup steps are referencing the not-built-in PowerShell 7. Windows PowerShell has the most compatibility since it's been built-in since Windows 7 I think.

It would probably make the most sense to have separate steps.

This is not so different from Mac's bash / zsh changeover a few major versions ago, but the "Windows PowerShell" vs "PowerShell" naming situation is more confusing.

**Comment by Schniz** [comment]
Can we just link to the doc I shared? Or should we mention $PROFILE?

**Comment by mikerochip** [comment]
I don't think that's enough because your doc link references PowerShell 7, which most likely few people have installed.

Probably the best thing to do is

1. Put the 2 different paths I mention in my last comment, for the different PowerShell versions
1. Link to [this doc](https://learn.microsoft.com/en-us/powershell/scripting/windows-powershell/install/installing-windows-powershell) to get people to understand that there are different PowerShells
1. Mention something like "if you're not sure, then probably you only have WindowsPowerShell installed because it's built-in"

It *should* be safe for users to create/modify both scripts to be safe but I haven't checked since I mainly use Mac.

Of course the best thing to do would be to script the shell changes so people don't have to worry about it.

Sorry, I would open a PR if I were an active user, but I actually chose to go with nvs instead of fnm, so it doesn't feel super appropriate. I came upon this thread because I was checking to see what the state of `winget` support was.
